package org.libprunus.core.plugin.aot.log

import net.bytebuddy.jar.asm.ClassReader
import net.bytebuddy.jar.asm.ClassVisitor
import net.bytebuddy.jar.asm.FieldVisitor
import net.bytebuddy.jar.asm.MethodVisitor
import net.bytebuddy.jar.asm.Opcodes
import org.libprunus.core.log.runtime.AbstractLogConfig
import spock.lang.Specification
import spock.lang.TempDir

class BindingClassGeneratorSpec extends Specification {

    private static final int JAVA_25_CLASS_FILE_VERSION = 69
    private static final List<String> SAMPLE_WHITELIST = ["java.util.Date", "java.lang.Number"]

    @TempDir
    File tempDir

    def "generate writes binding class file at fqcn path with generateBytes content"() {
        given:
        def generator = new BindingClassGenerator()
        def bindingClassName = "org.libprunus.aot.generated.b123.LogConfigBindingImpl"
        def target = new File(tempDir, "org/libprunus/aot/generated/b123/LogConfigBindingImpl.class")

        when:
        generator.generate(bindingClassName, tempDir.toPath(), "21", 128, SAMPLE_WHITELIST)

        then:
        target.exists()
        target.bytes == generator.generateBytes(bindingClassName, "21", 128, SAMPLE_WHITELIST)
    }

    def "generate rejects null binding class name with named NPE without writing any file"() {
        given:
        def generator = new BindingClassGenerator()

        when:
        generator.generate(null, tempDir.toPath(), "21", 128, SAMPLE_WHITELIST)

        then:
        def ex = thrown(NullPointerException)
        ex.message == "bindingClassName"
        tempDir.listFiles() == null || tempDir.listFiles().length == 0
    }

    def "generate rejects null output directory with named NPE without writing any file"() {
        given:
        def generator = new BindingClassGenerator()

        when:
        generator.generate(
                "org.libprunus.aot.generated.b123.LogConfigBindingImpl", null, "21", 128, SAMPLE_WHITELIST)

        then:
        def ex = thrown(NullPointerException)
        ex.message == "outputDir"
        tempDir.listFiles() == null || tempDir.listFiles().length == 0
    }

    def "generate leaves existing file untouched when generated bytes are unchanged"() {
        given:
        def generator = new BindingClassGenerator()
        def bindingClassName = "org.libprunus.aot.generated.b123.LogConfigBindingImpl"
        def target = new File(tempDir, "org/libprunus/aot/generated/b123/LogConfigBindingImpl.class")
        def expectedBytes = generator.generateBytes(bindingClassName, "21", 128, SAMPLE_WHITELIST)

        when:
        generator.generate(bindingClassName, tempDir.toPath(), "21", 128, SAMPLE_WHITELIST)
        def firstWriteBytes = target.bytes
        generator.generate(bindingClassName, tempDir.toPath(), "21", 128, SAMPLE_WHITELIST)
        def secondWriteBytes = target.bytes

        then:
        firstWriteBytes == expectedBytes
        secondWriteBytes == firstWriteBytes
    }

    def "generate overwrites same-sized stale content with generateBytes output"() {
        given:
        def generator = new BindingClassGenerator()
        def bindingClassName = "org.libprunus.aot.generated.b123.LogConfigBindingImpl"
        def target = new File(tempDir, "org/libprunus/aot/generated/b123/LogConfigBindingImpl.class")
        def expectedBytes = generator.generateBytes(bindingClassName, "21", 128, SAMPLE_WHITELIST)

        when:
        generator.generate(bindingClassName, tempDir.toPath(), "21", 128, SAMPLE_WHITELIST)
        target.bytes = new byte[expectedBytes.length]
        generator.generate(bindingClassName, tempDir.toPath(), "21", 128, SAMPLE_WHITELIST)

        then:
        target.bytes == expectedBytes
    }

    def "generateBytes emits binding class with expected name, version, super, fields and methods"() {
        given:
        def generator = new BindingClassGenerator()

        when:
        def bytes = generator.generateBytes(
                "org.libprunus.aot.generated.b123.LogConfigBindingImpl", "25", 256, SAMPLE_WHITELIST)
        def info = inspectClass(bytes)

        then:
        info.className == "org/libprunus/aot/generated/b123/LogConfigBindingImpl"
        info.version == JAVA_25_CLASS_FILE_VERSION
        info.superName == "org/libprunus/core/log/runtime/AbstractLogConfig"
        info.classAccess == (Opcodes.ACC_PUBLIC | Opcodes.ACC_FINAL)
        info.methods.collect { it.name }.toSet() == ["<init>", "<clinit>", "getMaxMessageLength", "isWhitelisted"].toSet()
        info.methods.size() == 4
        info.fields.toSet() == [
                [name: '$WHITELIST', descriptor: '[Ljava/lang/String;', access: Opcodes.ACC_PRIVATE | Opcodes.ACC_STATIC | Opcodes.ACC_FINAL],
                [name: '$WHITELIST_CACHE', descriptor: 'Ljava/lang/ClassValue;', access: Opcodes.ACC_PRIVATE | Opcodes.ACC_STATIC | Opcodes.ACC_FINAL]
        ].toSet()
        info.methods.find { it.name == "getMaxMessageLength" } == [name: "getMaxMessageLength", descriptor: "()I", access: Opcodes.ACC_PUBLIC]
        info.methods.find { it.name == "isWhitelisted" } == [name: "isWhitelisted", descriptor: "(Ljava/lang/Class;)Z", access: Opcodes.ACC_PUBLIC, signature: "(Ljava/lang/Class<*>;)Z"]
        info.methods.find { it.name == "<init>" } == [name: "<init>", descriptor: "()V", access: Opcodes.ACC_PUBLIC]
        info.methods.find { it.name == "<clinit>" } == [name: "<clinit>", descriptor: "()V", access: Opcodes.ACC_STATIC]
    }

    def "generateBytes produces a loadable binding class for a mid-scale whitelist with positive and negative membership"() {
        given:
        def whitelist = (1..1000).collect { "java.util.HashMap${it}".toString() }
        whitelist << "java.util.Date"

        when:
        def binding = loadBinding(whitelist)

        then:
        binding.isWhitelisted(Date)
        !binding.isWhitelisted(String)
    }

    def "generateBytes accepts whitelist with exactly MAX_WHITELIST_NAMES entries and produces a loadable class"() {
        given:
        def whitelist = (1..BindingClassGenerator.MAX_WHITELIST_NAMES).collect { "p.E${it}".toString() }
        def className = "org.libprunus.aot.generated.test.MaxImpl"

        when:
        def bytes = new BindingClassGenerator().generateBytes(className, "21", 128, whitelist)
        def info = inspectClass(bytes)

        then:
        info.methods.find { it.name == "<clinit>" } != null
        info.methods.find { it.name == "isWhitelisted" } != null
        bytes[0] == 0xCA as byte
        bytes[1] == 0xFE as byte
        bytes[2] == 0xBA as byte
        bytes[3] == 0xBE as byte
    }

    def "generateBytes throws IllegalStateException when whitelist size exceeds the maximum clinit bytecode limit"() {
        given:
        def whitelist = (1..(BindingClassGenerator.MAX_WHITELIST_NAMES + 1))
                .collect { "org.example.pojo.Entry${it}".toString() }

        when:
        new BindingClassGenerator().generateBytes("org.example.TestBinding", "21", 128, whitelist)

        then:
        def ex = thrown(IllegalStateException)
        ex.message.contains(String.valueOf(BindingClassGenerator.MAX_WHITELIST_NAMES + 1))
        ex.message.contains(String.valueOf(BindingClassGenerator.MAX_WHITELIST_NAMES))
        ex.message.contains("65535")
        ex.cause == null
    }

    def "emitClinit uses the smallest viable push opcode tier for whitelist array size and all indices"() {
        given:
        def whitelist = (0..<129).collect { "entry.${it}".toString() }
        def generator = new BindingClassGenerator()

        when:
        def bytes = generator.generateBytes("org.libprunus.aot.generated.test.TieredPushImpl", "21", 128, whitelist)
        def clinitOps = extractClinitOpcodes(bytes)

        then:
        clinitOps[0] == [type: 'intInsn', opcode: Opcodes.SIPUSH, operand: 129]
        clinitOps.any { it == [type: 'insn', opcode: Opcodes.ICONST_0] }
        clinitOps.any { it == [type: 'insn', opcode: Opcodes.ICONST_5] }
        clinitOps.any { it == [type: 'intInsn', opcode: Opcodes.BIPUSH, operand: 6] }
        clinitOps.any { it == [type: 'intInsn', opcode: Opcodes.BIPUSH, operand: 127] }
        clinitOps.any { it == [type: 'intInsn', opcode: Opcodes.SIPUSH, operand: 128] }
        !clinitOps.any { it.type == 'ldc' && it.value instanceof Integer }
    }

    def "emitClinit emits structural skeleton ANEWARRAY then per-entry DUP push LDC AASTORE then PUTSTATIC WHITELIST then INVOKESTATIC buildWhitelistCache then PUTSTATIC WHITELIST_CACHE then RETURN"() {
        given:
        def whitelist = ["a.A", "b.B", "c.C"]
        def generator = new BindingClassGenerator()

        when:
        def bytes = generator.generateBytes("org.libprunus.aot.generated.test.SkeletonImpl", "21", 128, whitelist)
        def ops = extractClinitOpcodes(bytes)
        def types = ops.findAll { it.type == 'type' }
        def fields = ops.findAll { it.type == 'field' }
        def methods = ops.findAll { it.type == 'method' }
        def aastoreCount = ops.count { it.type == 'insn' && it.opcode == Opcodes.AASTORE }
        def returnCount = ops.count { it.type == 'insn' && it.opcode == Opcodes.RETURN }

        then:
        types.size() == 1
        types[0].opcode == Opcodes.ANEWARRAY
        types[0].name == "java/lang/String"
        aastoreCount == 3
        methods.size() == 1
        methods[0].opcode == Opcodes.INVOKESTATIC
        methods[0].owner == "org/libprunus/core/log/runtime/LogRuntime"
        methods[0].name == "buildWhitelistCache"
        fields.collect { [opcode: it.opcode, name: it.name] } == [
                [opcode: Opcodes.PUTSTATIC, name: '$WHITELIST'],
                [opcode: Opcodes.PUTSTATIC, name: '$WHITELIST_CACHE']
        ]
        returnCount == 1
        ops.last() == [type: 'insn', opcode: Opcodes.RETURN]
    }

    def "clinit writes whitelist entries into the String array in caller-supplied order"() {
        given:
        def whitelist = ["a.A", "b.B", "c.C"]

        when:
        def bytes = new BindingClassGenerator().generateBytes(
                "org.libprunus.aot.generated.test.OrderImpl", "21", 128, whitelist)
        def ldcs = extractClinitOpcodes(bytes).findAll { it.type == 'ldc' && it.value instanceof String }

        then:
        ldcs*.value == whitelist
    }

    def "isWhitelisted dispatches to LogRuntime cache covering direct match, superclass and superinterface walk, miss, null type and empty whitelist"() {
        expect:
        loadBinding(whitelistNames).isWhitelisted(type) == expected

        where:
        whitelistNames             | type         || expected
        ["java.util.Date"]         | Date         || true
        ["java.lang.Number"]       | Number       || true
        ["java.lang.Number"]       | Long         || true
        ["java.lang.CharSequence"] | String       || true
        ["java.util.Date"]         | ArrayList    || false
        ["java.util.Date"]         | (Class) null || false
        []                         | Date         || false
    }

    def "loaded binding returns the maxMessageLength supplied to generateBytes verbatim across signed pushInt tiers"() {
        expect:
        loadBinding([], maxLen).getMaxMessageLength() == maxLen

        where:
        maxLen << [0, 5, 6, 127, 128, 32767, 32768, Integer.MAX_VALUE, -1, Integer.MIN_VALUE]
    }

    private AbstractLogConfig loadBinding(List<String> whitelistNames, int maxMessageLength = 128) {
        def className = "org.libprunus.aot.generated.test.BindingTestImpl"
        def bytes = new BindingClassGenerator().generateBytes(className, "21", maxMessageLength, whitelistNames)
        def loader = new ClassLoader(getClass().classLoader) {
            @Override
            Class<?> findClass(String name) throws ClassNotFoundException {
                if (name == className) {
                    return defineClass(name, bytes, 0, bytes.length)
                }
                throw new ClassNotFoundException(name)
            }
        }
        return loader.loadClass(className).getDeclaredConstructor().newInstance() as AbstractLogConfig
    }

    private static Map<String, Object> inspectClass(byte[] bytes) {
        def methods = []
        def fields = []
        def result = [:]
        new ClassReader(bytes).accept(new ClassVisitor(Opcodes.ASM9) {
            @Override
            void visit(int version, int access, String name, String signature, String superName, String[] interfaces) {
                result.className = name
                result.version = version
                result.superName = superName
                result.classAccess = access
            }

            @Override
            FieldVisitor visitField(
                    int access, String fieldName, String descriptor, String signature, Object value) {
                fields.add([name: fieldName, descriptor: descriptor, access: access])
                return null
            }

            @Override
            MethodVisitor visitMethod(
                    int access,
                    String methodName,
                    String methodDescriptor,
                    String signature,
                    String[] exceptions) {
                def m = [name: methodName, descriptor: methodDescriptor, access: access]
                if (signature != null) m.signature = signature
                methods.add(m)
                return null
            }
        }, 0)
        result.methods = methods
        result.fields = fields
        result
    }

    private static List<Map> extractClinitOpcodes(byte[] bytes) {
        def ops = []
        new ClassReader(bytes).accept(new ClassVisitor(Opcodes.ASM9) {
            @Override
            MethodVisitor visitMethod(
                    int access, String methodName, String descriptor, String signature, String[] exceptions) {
                if ("<clinit>" != methodName) return null
                return new MethodVisitor(Opcodes.ASM9) {
                    void visitInsn(int opcode) { ops << [type: 'insn', opcode: opcode] }
                    void visitIntInsn(int opcode, int operand) { ops << [type: 'intInsn', opcode: opcode, operand: operand] }
                    void visitLdcInsn(Object cst) { ops << [type: 'ldc', value: cst] }
                    void visitTypeInsn(int opcode, String t) { ops << [type: 'type', opcode: opcode, name: t] }
                    void visitFieldInsn(int opcode, String owner, String n, String d) {
                        ops << [type: 'field', opcode: opcode, owner: owner, name: n, descriptor: d]
                    }
                    void visitMethodInsn(int opcode, String owner, String n, String d, boolean itf) {
                        ops << [type: 'method', opcode: opcode, owner: owner, name: n, descriptor: d, itf: itf]
                    }
                }
            }
        }, 0)
        ops
    }
}
