[versions]
springBoot = "4.1.0"
dependencyAnalysis = "3.15.0"
libprunus = "0.1.2-SNAPSHOT"

[libraries]
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }
spring-boot-starter-batch-jdbc = { module = "org.springframework.boot:spring-boot-starter-batch-jdbc" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-batch-test = { module = "org.springframework.batch:spring-batch-test" }
h2 = { module = "com.h2database:h2" }
libprunus-bom = { module = "org.libprunus:libprunus-bom", version.ref = "libprunus" }
libprunus-core = { module = "org.libprunus:libprunus-core", version.ref = "libprunus" }
libprunus-spring = { module = "org.libprunus:libprunus-spring", version.ref = "libprunus" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
libprunus-core-plugin = { id = "org.libprunus.libprunus-core-plugin", version.ref = "libprunus" }
