create table if not exists product (
    id          bigint generated by default as identity primary key,
    sku         varchar(64)  not null unique,
    name        varchar(200) not null,
    category    varchar(100) not null,
    price_cents bigint       not null,
    quantity    int          not null
);
