package org.libprunus.core.log.annotation;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Container annotation for repeated {@link MethodLoggingProfile} declarations.
 *
 * <p>This annotation is typically generated by the compiler when multiple {@link
 * MethodLoggingProfile} annotations are declared on the same type.
 */
@Documented
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.CLASS)
public @interface MethodLoggingProfiles {

    /**
     * Declared method logging profiles.
     *
     * @return method logging routing profiles
     */
    MethodLoggingProfile[] value();
}
